Dev 2461
UbloImmo/front-tokens pull request #1
Opened 2024-01-16 15:10 UTC by blksnk

Tsc fixes

https://linear.app/ublo/issue/DEV-2461/clean-typescript

2024-01-16 16:38 UTC, Erwann20 requested changes

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/css.transformer.ts
> +        (styleNode as StyleNode<"EFFECT">).styleProperties,
Possible de passer par un prédicat plutôt qu'un cast ici ?

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/css.transformer.ts
> +    ? figmaPaintToCssProps((styleNode as StyleNode<"FILL">).styleProperties)
Possible de passer par un prédicat plutôt qu'un cast ici ?

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/export.transformer.ts
> +    tsReadonlyConst(constName, value as object)
Pourquoi ce cast ?

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/fill.transformer.ts
> +  switch (type) {
Possible de remplacer ce switch par une map ?

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/fill.transformer.ts
> +  switch (type) {
Ou pas des ifs

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/style.transformer.ts
> +  TStyleType extends Exclude<FigmaStyleType, "GRID">
Je vois qu'on utilise bcp "GRID", je pense que ce serait bien d'en faire une const

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/token.transfomer.ts
> +  if (type === "TEXT" || type === "EFFECT") return type;
"TEXT" et "EFFECT" et "FILL" dans une map.

Évitons d'avoir des magic strings comme ça surtout qu'on les réutilises plusieurs fois

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/token.transfomer.ts
> +  switch (tokenType) {
Essaie de remplacer ça par une map

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/token.transfomer.ts
> +        const currentSlicePath = (items as string[]).slice(level + 1).reverse();
On a besoin de ce cast ici ?

2024-01-16 16:38 UTC, Erwann20 commented on src/transformers/token.transfomer.ts
> +    typeof data.type === "string" &&
On utilise pas notre prédicat isString ici  ?

2024-01-16 16:38 UTC, Erwann20 commented on src/types/figma/figma.endpoints.types.ts
> +export type GetFileLocalVariablesEndpointResponse = {
Les types GetFileLocalVariablesEndpointResponse et GetFilePublishedVariablesEndpointResponse peuvent être mergé en faisant du générique ?

2024-01-16 16:38 UTC, Erwann20 commented on src/utils/string.utils.ts
> +    /[A-Z]+(?![a-z])|[A-Z]/g,
Regex à mettre dans une const avec un nom bien explicite

2024-01-16 17:31 UTC, blksnk commented on src/transformers/css.transformer.ts
> +    ? figmaPaintToCssProps((styleNode as StyleNode<"FILL">).styleProperties)
tu veux supprimer le switch du coup ?

2024-01-16 17:31 UTC, blksnk commented on src/transformers/style.transformer.ts
> +  TStyleType extends Exclude<FigmaStyleType, "GRID">
c'est une valeur d'enum donc cho

2024-01-16 17:32 UTC, blksnk commented on src/transformers/token.transfomer.ts
> +    typeof data.type === "string" &&
yes j'ai pas encore fait une passe partout pour utiliser la librairie utils

2024-01-16 17:33 UTC, blksnk commented on src/types/figma/figma.endpoints.types.ts
> +export type GetFileLocalVariablesEndpointResponse = {
Ca va compliquer la suite, je préfère avoir 1 type par endpoint pour pouvoir faire du conditionnel plus facilement par la suite

2024-01-16 18:00 UTC, blksnk commented on src/transformers/token.transfomer.ts
> +  switch (tokenType) {
c'est plus clair à la relecture avec un switch, surtout que ce code ne tourne qu'une fois à la génération

2024-01-17 11:10 UTC, Erwann20 approved these changes

2024-01-17 11:36 UTC, merged